# Setup
title:        <i>Machine learning</i> learning
tagline:      A blog about stuff I encounter on my <i>Machine learning</i> learning-journey
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Lucas van Walstijn
  url:        http://lucasvw.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true